### ISSUE TITLE
ILI9341 spi?

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_st7789_spi#1]
Hello,
I've found SPI version of ILI9341 320x240 TFT display in my reserves. How difficult it is to modify your ili9341_parallel code to work with SPI version?

**Comment by abhra0897** [comment]
Not at all. You can simply use the SPI part from the header file of this repo to make it work with ili9341. You need to define the correct pins, that's all.

**Comment by abhra0897** [comment]
You need to modify the .c file of ili9341 slightly too for CS pin. Just compare it with .c file of st7789.

**Comment by vitasam** [comment]
Thanks for the info! Will try it with a new board on stm32f103ret6

**Comment by vitasam** [comment]
Hello, 

I got it working:

![20200911_204649.jpg](https://user-images.githubusercontent.com/5597505/92959178-00801880-f474-11ea-98ea-c9e04faac500.jpg)

If you want, you can grab the code in my fork of your repo, the branch is: ili9341_spi

**Comment by abhra0897** [comment]
Hi! Great job... I'll add it to my ili9341 repo soon. Thanks a lot for adding the SPI support.

**Comment by vitasam** [comment]
You are welcome!

**Comment by vitasam** [comment]
Hello,
do you have such ILI9341 SPI TFT display? 

I'm a bit struggling now with my setup (the above photo) - it works with your test (see my branch `https://github.com/vitasam/stm32f1_ili9341_parallel/tree/ili9341_spi` )

But when I'm trying to move the same test under my stm32basic environment ( `https://github.com/vitasam/stm32basic/tree/stm32basic_hw20/tftspi_test_app`  ), the result is corrupted - e.g. both lines are horizontal at row 0 and fonts are not printed at all:

 
![20200913_161630](https://user-images.githubusercontent.com/5597505/93019080-70f67900-f5dd-11ea-9e7c-2b96c7cd1f7e.jpg)

Could you kindly guess what could be a problem?

Thank you!

**Comment by vitasam** [comment]
I have narrowed the problem down to a clock setup - the test is Ok with 128 MHz and corrupted with 72 MHz:
```
static void clock_setup(void)
{
	//rcc_clock_setup_in_hse_8mhz_out_128mhz();
	rcc_clock_setup_in_hse_8mhz_out_72mhz();
}
```

**Comment by abhra0897** [comment]
This problem is really confusing. If it was the other way around, i.e., working fine at 72MHz but corrupting at 128MHz, it would make some sense.

You may try these:
1.

```c
#define WRITE_8BIT(d)	do{ \
        while (SPI_SR(ILI_SPI) & SPI_SR_TXE); \
        SPI_DR(ILI_SPI) = (uint8_t)(d); \
        while (SPI_SR(ILI_SPI) & SPI_SR_BSY); \
} while(0)
```

2.

```c
#define ST_WRITE_8BIT(d)	do{ \
        SPI_DR(ST_SPI) = (uint8_t)(d); \
        /*while (SPI_SR(ST_SPI) & SPI_SR_BSY);*/ \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
} while(0)
```

3. 

Put breakpoints and check where it stops working. Start with writing a character and put a breakpoint at `ili_draw_pixel(temp_x, temp_y, back_color);`. Keep on stepping over and observe as the character is being rendered. 
Do a similar test for line drawing too. We need to know when/where it stops working properly.

**Comment by abhra0897** [comment]
Unfortunately, I don't have ili9341 spi display. So I can't test it.

**Comment by vitasam** [comment]
Thank you! Yes, it is confusing - I could expect some timing issues with higher clock but not other way around.

The method 2) did help:
```
#define WRITE_8BIT(d)	do{ \
        SPI_DR(ILI_SPI) = (uint8_t)(d); \
        /*while (SPI_SR(ST_SPI) & SPI_SR_BSY);*/ \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
        __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop"); \
} while(0)
```
Also confusing, should `while (SPI_SR(ILI_SPI) & SPI_SR_BSY);` stay there reliably?

**Comment by abhra0897** [comment]
`while (SPI_SR(ILI_SPI) & SPI_SR_BSY` is supposed to work reliably. At least it works in my st7789 driver. Though I later replaced it by nops to get higher throughput.

So, it's either while (SPI_SR(ILI_SPI) & SPI_SR_BSY or a bunch of nops - whatever is more stable.

Also, using DMA is a better option. I added DMA support in this repo, you may add it in your ili9341 spi repo.

**Comment by vitasam** [comment]
Hi,
I have found from this [forum](https://community.st.com/s/question/0D50X00009XkfQK/stm32f4-spi-busy-flag):

_''During discontinuous communications, there is a 2 APB clock period delay between the
write operation to SPI_DR and the BSY bit setting. As a consequence, in transmit-only
mode, it is mandatory to wait first until TXE is set and then until BSY is cleared after writing the last data.''_

So, this code works for me for 72 MHz:

```
#define WRITE_8BIT(d)	do{ \
        SPI_DR(ILI_SPI) = (uint8_t)(d); \
        while (!(SPI_SR(ILI_SPI) & SPI_SR_TXE)); \
        while (SPI_SR(ILI_SPI) & SPI_SR_BSY); \
} while(0)
```

**Comment by abhra0897** [comment]
Awesome! :) 

Yes, I've found in the reference manual too. Actually, I've written my solution 1 wrong. TXE check should be right before BSY check (like you did).

Anyways, as per my tests, using nops gives considerably higher write speed than TXE and BSY flag checking. As my driver's main focus is speed, I opted for nops.

**Comment by vitasam** [comment]
Yep, I see, `nop` is definitely faster. But for stm32basic purpose registers&flags are Ok, since it is reliable on every HW and I don't need high FPS. 
Maybe later I will incorporate your DMA code but right now I have to move TFT code in to stm32basic HW 2.0

Thanks for a help!

**Comment by abhra0897** [comment]
You're welcome.

If I had a PS/2 keyboard, I could try out your stm32basic. I couldn't find any PS/2 keyboard at reasonable price locally.

**Comment by vitasam** [comment]
Great! Maybe you can find PS/2 keyboard in electronic waste places of workshops and stores.

**Comment by vitasam** [comment]
![20200914_204426.jpg](https://user-images.githubusercontent.com/5597505/93119970-55699c00-f6cb-11ea-8093-3cb532030a44.jpg)

**Comment by abhra0897** [comment]
Looks great! So, everything's stable now?
I'll add your spi code in my repo once I get some free time.

**Comment by vitasam** [comment]
Hi,
yes, everything is stable now. The latest SPI TFT code is in my `stm32basic` repo, in  `/stm32basic_hw20` branch:
`https://github.com/vitasam/stm32basic/tree/stm32basic_hw20`:

`/include` and `/src`, also I've renamed files accordingly.
